#ifndef BASICSHAPEPLUGIN_GLOBAL_H
#define BASICSHAPEPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BASICSHAPEPLUGIN_LIBRARY)
#  define BASICSHAPEPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define BASICSHAPEPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // BASICSHAPEPLUGIN_GLOBAL_H
